USE [Twitt]

GO

CREATE TABLE [Post]
(
	[ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Message] VARCHAR(200),
	[Picture] VARBINARY NULL,
	[ProfileID] INT NOT NUll,
	FOREIGN KEY ([ProfileID]) REFERENCES [Profile](ID)
)

GO